update

diff --git a/Small_5/package/ipk/luci-app-overwall/root/usr/share/overwall/update b/Small_5/package/ipk/luci-app-overwall/root/usr/share/overwall/update
--- a/Small_5/package/ipk/luci-app-overwall/root/usr/share/overwall/update
+++ b/Small_5/package/ipk/luci-app-overwall/root/usr/share/overwall/update
@@ -10,6 +10,8 @@ TMP=/tmp/overwall
 X=$(lua /usr/share/overwall/auth A)/2axgmlws/KkFCtZkeAP
 Y=$(lua /usr/share/overwall/auth B)
 Z="lua /usr/share/overwall/auth C"
+N=overwall
+C=$(uci -q get $N.@global[0].run_mode)
 
 log(){
 	[ $A = N ] && echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> /tmp/overwall.log
@@ -21,31 +23,32 @@ clean(){
 	exit 1
 }
 
-if [ $A = Y ];then
-	mkdir -p $TMP
-	r=1
-	while ! B=$(curl -Lfsm 20 -A "$Y" $X/eFw58nNRXXfTwU4$(eval $Z));do
-		[ $r -ge 20 ] && clean || let r++
-		sleep 2
-	done
-else
-	B=$(curl -Lfsm 20 -A "$Y" $X/eFw58nNRXXfTwU4$(eval $Z))
-fi
-if [ "$B" ];then
-	echo "$B" | base64 -d > /tmp/ipv4.txt
-	if cmp -s /tmp/ipv4.txt $TMP/ipv4.txt;then
-		log "Over Update  : IPv4 List is up to date"
+if [ $C = router ] || [ $C = gfw -a "$(uci -q get $N.@access_control[0].lan_gm_ips)" ] || [ $C = oversea ];then
+	if [ $A = Y ];then
+		mkdir -p $TMP
+		r=1
+		while ! B=$(curl -Lfsm 20 -A "$Y" $X/eFw58nNRXXfTwU4$(eval $Z));do
+			[ $r -ge 20 ] && clean || let r++
+			sleep 2
+		done
 	else
-		log "Over Update  : Update IPv4 List"
-		cp -f /tmp/ipv4.txt $TMP/ipv4.txt
-		[ $A = N ] && ipset list over_v4 >/dev/null 2>&1 && $DIR/ipset
+		B=$(curl -Lfsm 20 -A "$Y" $X/eFw58nNRXXfTwU4$(eval $Z))
 	fi
-else
-	log "Over Update  : Download IPv4 List failed"
+	if [ "$B" ];then
+		echo "$B" | base64 -d > /tmp/ipv4.txt
+		if cmp -s /tmp/ipv4.txt $TMP/ipv4.txt;then
+			log "Over Update  : IPv4 List is up to date"
+		else
+			log "Over Update  : Update IPv4 List"
+			cp -f /tmp/ipv4.txt $TMP/ipv4.txt
+			[ $A = N ] && ipset list over_v4 >/dev/null 2>&1 && $DIR/ipset
+		fi
+	else
+		log "Over Update  : Download IPv4 List failed"
+	fi
 fi
 
-C=$(uci -q get overwall.@global[0].run_mode)
-if [ "$C" = router ];then
+if [ $C = router ];then
 	if [ $A = Y ];then
 		mkdir -p $TMP
 		while ! D=$(curl -Lfsm 20 -A "$Y" $X/t8eOh94EJIHTXR6$(eval $Z));do
@@ -68,7 +71,7 @@ if [ "$C" = router ];then
 	fi
 fi
 
-if [ "$C" = gfw -o ! $(uci -q get overwall.@global[0].gfw_mode) ];then
+if [ $C = gfw ] || [ $C = router -a ! $(uci -q get $N.@global[0].gfw_mode) ];then
 	if [ $A = Y ];then
 		while ! curl -Lfsm 20 -A "$Y" -o /tmp/gfw.b64 $X/avtPeqDKt645Arm$(eval $Z);do
 			sleep 2
