Update adblock-plus

diff --git a/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/adblock b/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/adblock
--- a/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/adblock
+++ b/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/adblock
@@ -17,11 +17,12 @@ E="date +'%Y-%m-%d %H:%M:%S'"
 U=`uci -q get adblock.@adblock[0].url`
 P=/tmp/adblock
 W=`cat /etc/adblock/white.list`
+H=$(lua /usr/share/adblock/auth A)/ad-rules
+I=$(lua /usr/share/adblock/auth B)
+J="lua /usr/share/adblock/auth C"
 
 gen(){
-	cat /tmp/adnew.conf | grep ^\|\|[^\*]*\^$ | grep -Ev "^\|\|[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}*" | sed -e 's:||:address=/:' -e 's:\^:/:' > /tmp/ad.conf
 	for i in $W;do sed -i -e "/\/$i\//d" -e "/\.$i\//d" /tmp/ad.conf;done
-	rm -f /tmp/adnew.conf
 }
 
 down(){
@@ -31,13 +32,23 @@ down(){
 	mkdir -p $G
 	for i in $U;do
 		X=1
-		while ! curl --connect-timeout 5 -m 20 -Lfso $F $i;do
+		case $i in
+			adguard|anti-ad|ad-wars)K="curl -m 20 -A '$I' -Lfso $F $H/$i$(eval $J)";;
+			*)K="curl -m 20 -Lfso $F $i";;
+		esac
+		while ! eval $K;do
 			[ $X -ge 20 ] && echo "`eval $E` [Download $i Failed]" && continue 2 || let X++
 			sleep 2
+			case $i in
+				adguard|anti-ad|ad-wars)K="curl -m 20 -A '$I' -Lfso $F $H/$i$(eval $J)";;
+			esac
 		done
 		X=`md5sum $G/3rd.conf 2>/dev/null | awk '{print$1}'`
 		Y=`md5sum $G/host 2>/dev/null | awk '{print$1}'`
-		sed -i 's/\r/\n/g' $F;sed -i -e '/127.0.0.1 #/d' -e '/127.0.0.1 !/d' -e 's:#.*::' -e 's:!.*::' -e 's/\$.*//g' -e 's/[ \t]*$//g' -e 's/^[ \t]*//g' -e '/\*/d' -e '/^$/d' $F
+		case $i in
+			adguard|anti-ad|ad-wars);;
+			*)sed -i 's/\r/\n/g' $F;sed -i -e '/127.0.0.1 #/d' -e '/127.0.0.1 !/d' -e 's:#.*::' -e 's:!.*::' -e 's/\$.*//g' -e 's/[ \t]*$//g' -e 's/^[ \t]*//g' -e '/\*/d' -e '/^$/d' $F;;
+		esac
 		if grep -q "^address=" $F;then
 			cat $F >> $G/3rd.conf
 		elif grep -q -e "^0.0.0.0 " -e "^127.0.0.1 " $F;then
@@ -93,8 +104,16 @@ case $1 in
 esac
 
 if [ `uci -q get adblock.@adblock[0].enable` = 1 ];then
-	G=`curl -LSfso /tmp/adnew.conf https://small_5.coding.net/p/ad-rules/d/ad-rules/git/raw/master/easylistchina%2Beasylist.txt 2>&1 || curl -LSfso /tmp/adnew.conf https://cdn.jsdelivr.net/gh/small-5/ad-rules/easylistchina+easylist.txt 2>&1`
-	if [ $? = 0 ];then
+	echo "`eval $E` [$A]"
+	X=1
+	while ! G=`curl -m 20 -A "$I" -LfSso /tmp/ad.conf $H/dnsmasq.adblock$(eval $J) 2>&1`;do
+		[ $X -ge 20 ] && Y=1 && return || let X++
+		sleep 2
+	done
+	if [ "$Y" = 1 ];then
+		echo "`eval $E` [$A Failed]"
+		echo -e "$G\n"
+	else
 		echo "`eval $E` [$A Successful]"
 		gen
 		if ! cmp -s /tmp/ad.conf $P/adblock.conf;then
@@ -104,12 +123,9 @@ if [ `uci -q get adblock.@adblock[0].enable` = 1 ];then
 		else
 			echo "`eval $E` [Adblock Plus Rules No Change]"
 		fi
-	else
-		echo "`eval $E` [$A Failed]"
-		echo -e "$G\n"
 	fi
 	rm -f /tmp/ad.conf
-	[ -n "$U" ] && down
+	[ "$U" ] && echo "`eval $E` [$B]" && down
 	echo `eval $E` > $P/adblock.updated
 fi
 
