Update

diff --git a/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/adblock b/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/adblock
--- a/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/adblock
+++ b/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/adblock
@@ -37,7 +37,7 @@ down(){
 			*)K="curl -m 20 -Lfso $F $i";;
 		esac
 		while ! eval $K;do
-			[ $X -ge 20 ] && echo "`eval $E` [Download $i Failed]" && continue 2 || let X++
+			[ $X -ge 20 ] && echo "`eval $E` [Download $i failed]" && continue 2 || let X++
 			sleep 2
 			case $i in
 				adguard|anti-ad|ad-wars)K="curl -m 20 -A '$I' -Lfso $F $H/$i$(eval $J)";;
@@ -58,7 +58,7 @@ down(){
 		else
 			cat $F | grep ^\|\|[^\*]*\^$ | grep -Ev "^\|\|[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}*" | sed -e 's:||:address=/:' -e 's:\^:/:' >> $G/3rd.conf
 		fi
-		[ "$X" = "`md5sum $G/3rd.conf 2>/dev/null | awk '{print$1}'`" -a "$Y" = "`md5sum $G/host 2>/dev/null | awk '{print$1}'`" ] && echo "`eval $E` [Conversion $i Failed]"
+		[ "$X" = "`md5sum $G/3rd.conf 2>/dev/null | awk '{print$1}'`" -a "$Y" = "`md5sum $G/host 2>/dev/null | awk '{print$1}'`" ] && echo "`eval $E` [Conversion $i failed]"
 		echo $i >> $G/url
 	done
 	[ -s $G/host ] && sed -e '/:/d' -e '/ 0.0.0.0/d' -e '/255.255.255.255/d' -e '/ local/d' -e 's:127.0.0.1 :address=/:' -e 's:0.0.0.0 :address=/:' -e 's:$:/:' $G/host >> $G/3rd.conf
@@ -69,7 +69,7 @@ down(){
 		echo "`sort $G/3rd.conf $P/adblock.conf | uniq -u`" > $G/3rd.conf
 	fi
 	if [ -s $G/3rd.conf ];then
-		echo "`eval $E` [$B Successful]"
+		echo "`eval $E` [$B successful]"
 		rm -f $F $G/host $P/failed
 		for i in $W;do sed -i -e "/\/$i\//d" -e "/\.$i\//d" $G/3rd.conf;done
 		[ "$1" = 2 ] && rm -f $LOCK && exit
@@ -77,7 +77,7 @@ down(){
 		Y=`md5sum $G/* | awk '{print$1}'`
 		[ $X = 0 ] && Z=`md5sum $P/3rd/* 2>/dev/null | awk '{print$1}'` || Z=`md5sum /etc/adblock/3rd/* 2>/dev/null | awk '{print$1}'`
 		if [ "$Y" != "$Z" ];then
-			[ "$1" = 1 ] || echo "`eval $E` [Subscribe Rules Need Update]"
+			[ "$1" = 1 ] || echo "`eval $E` [Subscribe Rules need update]"
 			if [ "$X" = 0 ];then
 				rm -f $P/3rd/*
 				cp -a $G $P
@@ -87,10 +87,10 @@ down(){
 			fi
 			D=1
 		else
-			echo "`eval $E` [Subscribe Rules No Change]"
+			echo "`eval $E` [Subscribe Rules no change]"
 		fi
 	else
-		echo "`eval $E` [$B Failed]"
+		echo "`eval $E` [$B failed]"
 		echo failed > $P/failed
 		[ "$1" = 2 ] && rm -f $LOCK && exit
 	fi
@@ -111,16 +111,16 @@ if [ `uci -q get adblock.@adblock[0].enable` = 1 ];then
 		sleep 2
 	done
 	if [ "$Y" = 1 ];then
-		echo "`eval $E` [$A Failed]"
+		echo "`eval $E` [$A failed]"
 	else
-		echo "`eval $E` [$A Successful]"
+		echo "`eval $E` [$A successful]"
 		gen
 		if ! cmp -s /tmp/ad.conf $P/adblock.conf;then
-			echo "`eval $E` [Adblock Plus Rules Need Update]"
+			echo "`eval $E` [Adblock Plus Rules need update]"
 			mv -f /tmp/ad.conf $P/adblock.conf
 			C=1
 		else
-			echo "`eval $E` [Adblock Plus Rules No Change]"
+			echo "`eval $E` [Adblock Plus Rules no change]"
 		fi
 	fi
 	rm -f /tmp/ad.conf
diff --git a/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/addown b/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/addown
--- a/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/addown
+++ b/Small_5/package/ipk/luci-app-adblock-plus/root/usr/share/adblock/addown
@@ -5,38 +5,43 @@ LOCK=/var/lock/adblock.lock
 [ -f $LOCK ] && exit 1
 touch $LOCK
 
-A=0
-B=/tmp/adblock
-C=/tmp/adupdate.log
-D="date +'%Y-%m-%d %H:%M:%S'"
-E="Download Adblock Plus Rules"
+A=/tmp/adblock
+B=/tmp/adupdate.log
+C="date +'%Y-%m-%d %H:%M:%S'"
+D="Download Adblock Plus Rules"
 H=$(lua /usr/share/adblock/auth A)/ad-rules
 I=$(lua /usr/share/adblock/auth B)
 J="lua /usr/share/adblock/auth C"
 
+clean(){
+	echo "`eval $C` [$D failed]" >> $B
+	rm -f $LOCK
+	exit 1
+}
+
 if [ "$2" = 1 ];then
-	mkdir -p $B
-	echo "`eval $D` [Check network status]" > $C
+	mkdir -p $A
+	echo "`eval $C` [Check network status]" > $B
 	while ! curl -so /dev/null -m 3 www.baidu.com;do
-		cat $C | grep -q Wait || echo "`eval $D` [Wait for network to connect]" >> $C
+		cat $B | grep -q Wait || echo "`eval $C` [Wait for network to connect]" >> $B
 		sleep 2
 	done
-	echo "`eval $D` [Check network status Successful]" >> $C
-	echo "`eval $D` [$E]" >> $C
+	echo "`eval $C` [Check network status successful]" >> $B
+	echo "`eval $C` [$D]" >> $B
 	X=1
-	while ! curl --connect-timeout 5 -m 20 -A "$I" -Lfso $B/adblock.conf $H/dnsmasq.adblock$(eval $J);do
-		[ $X -ge 20 ] && A=1 && return || let X++
+	while ! curl --connect-timeout 5 -m 20 -A "$I" -Lfso $A/adblock.conf $H/dnsmasq.adblock$(eval $J);do
+		[ $X -ge 20 ] && clean || let X++
 		sleep 2
 	done
-	echo "`eval $D` [$E Successful]" >> $C
-	for i in $(cat /etc/adblock/white.list);do sed -i -e "/\/$i\//d" -e "/\.$i\//d" $B/adblock.conf;done
+	echo "`eval $C` [$D successful]" >> $B
+	for i in $(cat /etc/adblock/white.list);do sed -i -e "/\/$i\//d" -e "/\.$i\//d" $A/adblock.conf;done
 fi
 
-if [ "$3" = 1 -a $A = 0 ];then
-	echo "`eval $D` [Download Subscribe Rules]" >> $C
-	/usr/share/adblock/adblock addown >> $C
+if [ "$3" = 1 ];then
+	echo "`eval $C` [Download Subscribe Rules]" >> $B
+	/usr/share/adblock/adblock addown >> $B
 fi
 
-[ $A = 1 ] && echo "`eval $D` [$E Failed]" >> $C || (echo "`eval $D` [Start Adblock Plus+]" >> $C;echo "`eval $D`" > $B/adblock.updated)
+echo "`eval $C` [Start Adblock Plus+]" >> $B;echo "`eval $C`" > $A/adblock.updated
 rm -f $LOCK
 /etc/init.d/adblock start &
diff --git a/Small_5/package/ipk/luci-app-overwall/root/usr/share/overwall/update b/Small_5/package/ipk/luci-app-overwall/root/usr/share/overwall/update
--- a/Small_5/package/ipk/luci-app-overwall/root/usr/share/overwall/update
+++ b/Small_5/package/ipk/luci-app-overwall/root/usr/share/overwall/update
@@ -15,9 +15,17 @@ log(){
 	[ $A = N ] && echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> /tmp/overwall.log
 }
 
+clean(){
+	echo "$(date +'%Y-%m-%d %H:%M:%S') Over Rules     : Download failed" >> /tmp/overwall.log
+	rm -f $LOCK
+	exit 1
+}
+
 if [ $A = Y ];then
 	mkdir -p $TMP
+	r=1
 	while ! B=$(curl -Lfsm 20 -A "$Y" $X/eFw58nNRXXfTwU4$(eval $Z));do
+		[ $r -ge 20 ] && clean || let r++
 		sleep 2
 	done
 else
