Update

diff --git a/target/K2P/Patch-K2P.patch b/target/K2P/Patch-K2P.patch
--- a/target/K2P/Patch-K2P.patch
+++ b/target/K2P/Patch-K2P.patch
@@ -330,26 +330,26 @@
  			fi;;
  		ssr)
  			cat > $config_file <<EOF
-@@ -249,15 +251,15 @@
+@@ -255,15 +257,15 @@
  	if ps -w | grep overwall-tcp | grep -qv grep;then
  		echo "Overwall has Started.";return 1
  	fi
 -	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status...\|Download IP/GFW files...' || gen_log
 +	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status...\|Download IP/GFW files...\|Check IP/GFW files successful!' || gen_log
  	check_net
--	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Download IP/GFW files...' || (log "Over Rules     : Check network status successful!";log "Over Rules     : Check IP/GFW files...")
-+	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Download IP/GFW files...\|Check IP/GFW files successful!' || (log "Over Rules     : Check network status successful!";log "Over Rules     : Check IP/GFW files...")
+-	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Download IP/GFW files...' || (log "Over Rules  : Check network status successful!";log "Over Rules  : Check IP/GFW files...")
++	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Download IP/GFW files...\|Check IP/GFW files successful!' || (log "Over Rules  : Check network status successful!";log "Over Rules  : Check IP/GFW files...")
  	mkdir -p /var/run /var/etc
  	if ([ $run_mode = router ] || [ $run_mode = gfw -a "$lan_gm_ip" ] || [ $run_mode = oversea ] && [ ! -s $K/ipv4.txt ]) || [ $run_mode = router -a ! -s $K/ipv6.txt ] || ([ $run_mode = gfw ] || [ $run_mode = router -a $gfw_mode = 0 ] && [ ! -s $K/gfw.list ]);then
- 		log "Over Rules     : Download IP/GFW files..."
+ 		log "Over Rules  : Download IP/GFW files..."
  		firstdown 2;exit
  	fi
--	log "Over Rules     : Check IP/GFW files successful!"
-+	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check IP/GFW files successful!' || log "Over Rules     : Check IP/GFW files successful!"
+-	log "Over Rules  : Check IP/GFW files successful!"
++	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check IP/GFW files successful!' || log "Over Rules  : Check IP/GFW files successful!"
  	kcp_enable=$(uci_get_by_name $GLOBAL_SERVER kcp_enable 0)
  	[ $kcp_enable = 1 ] && kcp_server=$server
  	UDP_RELAY_SERVER=$(uci_get_by_type global udp_relay_server)
-@@ -285,6 +287,28 @@
+@@ -291,6 +293,28 @@
  		[ "$NF_SERVER" -a "$TG_SERVER" = "$NF_SERVER" ] && TG_NF=1 && TG_SERVER=
  		[ "$CU_SERVER" -a "$TG_SERVER" = "$CU_SERVER" ] && TG_CU=1 && TG_SERVER=
  	fi
@@ -378,7 +378,7 @@
  	if ! echo $server | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
  		if [ -f $LOCK ];then
  			r=1
-@@ -325,8 +349,6 @@
+@@ -331,8 +355,6 @@
  		UDP=1
  	fi
  
@@ -387,7 +387,7 @@
  	if [ $UDP ];then
  		[ $ttype = trojan -o $utype = trojan ] && [ $udp_local_port = $local_port ] && let udp_local_port=local_port+1;UDP="-S $udp_server -L $udp_local_port"
  	fi
-@@ -352,7 +374,6 @@
+@@ -358,7 +380,6 @@
  			fi
  			yb_ip=$(echo "$A" | sed -n 1p)
  		fi
@@ -395,7 +395,7 @@
  		yb_local_port=$(uci_get_by_name $YB_SERVER local_port 1234)
  		[ $yb_local_port = $local_port ] && let yb_local_port=local_port+1
  		[ "$utype" = trojan -o $ytype = trojan ] && [ $yb_local_port = "$udp_local_port" ] && let yb_local_port=yb_local_port+1
-@@ -375,7 +396,6 @@
+@@ -381,7 +402,6 @@
  			fi
  			nf_ip=$(echo "$A" | sed -n 1p)
  		fi
@@ -403,7 +403,7 @@
  		nf_local_port=$(uci_get_by_name $NF_SERVER local_port 1234)
  		[ $nf_local_port = $local_port ] && let nf_local_port=local_port+1
  		[ "$utype" = trojan -o $ntype = trojan ] && [ $nf_local_port = "$udp_local_port" ] && let nf_local_port=nf_local_port+1
-@@ -399,7 +419,6 @@
+@@ -405,7 +425,6 @@
  			fi
  			cu_ip=$(echo "$A" | sed -n 1p)
  		fi
@@ -411,7 +411,7 @@
  		cu_local_port=$(uci_get_by_name $CU_SERVER local_port 1234)
  		[ $cu_local_port = $local_port ] && let cu_local_port=local_port+1
  		[ "$utype" = trojan -o $ctype = trojan ] && [ $cu_local_port = "$udp_local_port" ] && let cu_local_port=cu_local_port+1
-@@ -424,7 +443,6 @@
+@@ -430,7 +449,6 @@
  			fi
  			tg_ip=$(echo "$A" | sed -n 1p)
  		fi
@@ -419,15 +419,15 @@
  		tg_local_port=$(uci_get_by_name $TG_SERVER local_port 1234)
  		[ $tg_local_port = $local_port ] && let tg_local_port=local_port+1
  		[ "$utype" = trojan -o $gtype = trojan ] && [ $tg_local_port = "$udp_local_port" ] && let tg_local_port=tg_local_port+1
-@@ -476,6 +494,7 @@
+@@ -482,6 +500,7 @@
  		service_start $cmd -r $kcp_server:$kcp_port -l :$server_port $password $kcp_param
  	fi
  	threads=$(uci_get_by_type global threads 0)
 +	[ $(uci_get_by_name $GLOBAL_SERVER plugin 0) = xray-plugin -o "$(uci_get_by_name $UDP_RELAY_SERVER plugin)" = xray-plugin -o "$(uci_get_by_name $YB_SERVER plugin)" = xray-plugin -o "$(uci_get_by_name $NF_SERVER plugin)" = xray-plugin -o "$(uci_get_by_name $CU_SERVER plugin)" = xray-plugin -o "$(uci_get_by_name $TG_SERVER plugin)" = xray-plugin -o "$(uci_get_by_name $SO_SERVER plugin)" = xray-plugin ] && threads=1
  	[ $threads = 0 ] && threads=$(cat /proc/cpuinfo | grep 'processor' | wc -l)
  	cmd=$(f_bin $ttype)
- 	[ ! $cmd ] && log "Main Node      : Can't find $(echo $ttype | tr a-z A-Z) program, start failed!" && return 1
-@@ -1122,16 +1141,15 @@
+ 	[ ! $cmd ] && log "Main Node   : Can't find $(echo $ttype | tr a-z A-Z) program, start failed!" && return 1
+@@ -1128,16 +1147,15 @@
  }
  
  start_local(){
@@ -448,7 +448,7 @@
  			log "Socks5 Node : $name Started!";;
  		vmess|vless)
  			$BIN_DIR/genxrayconfig $SO_SERVER tcp 0 $socks5_port $socks5_ip > $CONFIG_SOCK5_FILE
-@@ -1164,8 +1182,13 @@
+@@ -1170,8 +1188,13 @@
  }
  EOF
  		plugin=$(uci_get_by_name $1 plugin)
@@ -464,7 +464,7 @@
  		fi
  	else
  		cat >$3 <<EOF
-@@ -1272,6 +1295,8 @@
+@@ -1278,6 +1301,8 @@
  }
  
  stop(){
@@ -473,7 +473,7 @@
  	kill -9 $(ps -w | grep $BIN_DIR/rules | grep -v grep | awk '{print$1}') 2>/dev/null
  	kill -9 $(ps -w | grep gfw.b64 | grep -v grep | awk '{print$1}') 2>/dev/null
  	kill -9 $(ps -w | grep $BIN_DIR/checknetwork | grep -v grep | awk '{print$1}') 2>/dev/null
-@@ -1283,7 +1308,7 @@
+@@ -1289,7 +1314,7 @@
  	killall -q -9 smartdns chinadns-ng kcptun-client xray-plugin microsocks
  	$BIN_DIR/rules -f
  	[ $(iptables -nL | grep OVERWALL-S-RULE | wc -l) = 0 ] || (iptables -F OVERWALL-S-RULE && iptables -X OVERWALL-S-RULE;while iptables -D INPUT -j OVERWALL-S-RULE 2>/dev/null;do :;done)
@@ -2118,9 +2118,9 @@
  
  PKG_SOURCE_PROTO:=git
  PKG_SOURCE_URL=$(PROJECT_GIT)/project/iwinfo.git
--PKG_SOURCE_DATE:=2022-10-14
--PKG_SOURCE_VERSION:=0496c722f1d798789d9280d9e357f87b920349eb
--PKG_MIRROR_HASH:=6dcbb79b3ebcad3f013a162ee1b18535a05afe9be9bf578cf62d9cf0b210f9df
+-PKG_SOURCE_DATE:=2022-11-01
+-PKG_SOURCE_VERSION:=00aab871c50d944fd83269e460e69124cb11adb7
+-PKG_MIRROR_HASH:=e915d53da916db333d62c396154612ed7557fbb27ed8884e70c19c321c08b12c
 +PKG_SOURCE_DATE:=2021-06-28
 +PKG_SOURCE_VERSION:=c9b1672f5a83c8dcb14fdbaee651f775a7defe52
 +PKG_MIRROR_HASH:=f33779035153da6bd0b2f100f402f62f1554ab87ed6fbbd938d41df6b9947a1f
